import React from "react";

// Unified reusable card component
export default function UnifiedCard({ image, title, children, className = "" }) {
                                                                                return (
                                                                                                                                                                <div
                                                                                                                                                                                                                                                className={`bg-white rounded-xl shadow-md p-4 flex flex-col items-center transition-transform hover:scale-105 border border-gray-100 ${className}`}
                                                                                                                                                                                                                                                style={{ width: 200, minHeight: 260 }}
                                                                                                                                                                >
                                                                                                                                                                                                                                                {image && (
                                                                                                                                                                                                                                                                                                                                <img
                                                                                                                                                                                                                                                                                                                                                                                                                src={image}
                                                                                                                                                                                                                                                                                                                                                                                                                alt={title}
                                                                                                                                                                                                                                                                                                                                                                                                                className="w-24 h-24 object-contain mb-3 rounded-lg border border-gray-200 bg-gray-50"
                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                {title && (
                                                                                                                                                                                                                                                                                                                                <h3 className="text-lg font-semibold text-gray-800 mb-2 text-center truncate w-full" title={title}>
                                                                                                                                                                                                                                                                                                                                                                                                                {title}
                                                                                                                                                                                                                                                                                                                                </h3>
                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                <div className="flex-1 w-full flex flex-col items-center justify-center">{children}</div>
                                                                                                                                                                </div>
                                                                                );
} 